language: go
go_import_path: github.com/dicot-project/dicot-api
sudo: false
dist: trusty

go:
- 1.8
- 1.9

install:
 - git reset --hard
 - go get github.com/golang/dep/cmd/dep

script:
 - make

cache:
  directories:
  - vendor
