apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: flavors.dicot.io
spec:
  scope: Namespaced
  group: dicot.io
  version: v1alpha1
  names:
    kind: Flavor
    plural: flavors
    singular: flavor
